### ISSUE TITLE
[ENH] Remove server requirement to local previews and gh-pages compat

### ISSUE THREAD

**Issue by mmcky** [QuantEcon/quantecon-book-theme#10]
**Priority:** HIGH

The `sphinx-book-theme` doesn't require a server to preview. 

I would like the same for this theme. 

So we can just open `_build/html/index.html`

Changing the priority on this to high as it looks like it is also needed for `gh-pages` compatibility.

**Comment by mmcky** [comment]
@DrDrij can we remove this dependency easily?

**Comment by AakashGfude** [comment]
The thing missing in `quantecon-book-theme` is the header buttons it seems.
Local preview without a server:

<img width="1789" alt="Screen Shot 2020-10-02 at 10 34 49 am" src="https://user-images.githubusercontent.com/6542997/94876504-2c068980-049b-11eb-87a2-a7067ba13b56.png">

**Comment by DrDrij** [comment]
Hmm the button icons require `plugins.js`. Possibly the link there isn't relative. I *think* removing the forward slash here might help.
https://github.com/QuantEcon/quantecon-book-theme/blob/f85ed6cd3ecda54bb904f7ed9266d1b4877f3080/quantecon_book_theme/layout.html#L168

**Comment by mmcky** [comment]
@AakashGfude can you look into this link so that this could be viewed without a server?

**Comment by AakashGfude** [comment]
> Hmm the button icons require `plugins.js`. Possibly the link there isn't relative. I _think_ removing the forward slash here might help.
> https://github.com/QuantEcon/quantecon-book-theme/blob/f85ed6cd3ecda54bb904f7ed9266d1b4877f3080/quantecon_book_theme/layout.html#L168

yup. this does the job @DrDrij . have checked.
