### ISSUE TITLE
MAINT: Improve quantecon-book-theme release mechanism

### ISSUE THREAD

**Issue by mmcky** [QuantEcon/quantecon-book-theme#106]
The current release `quantecon-book-theme=0.1.5` is missing the latest css file. 

We need to:

- [x] release `quantecon-book-theme=0.1.6` with all assets updated (for PR https://github.com/QuantEcon/lecture-python.myst/pull/132)
- [x] setup an `automated` release mechanism so this doesn't happen again
- [ ] document the release process on the `wiki`
- [x] setup `releases` using `github actions` and automatic publishing to `pypi` through `github release` and `tag` creation.

**Comment by mmcky** [comment]
@AakashGfude I know there are a lot of balls in the air at the moment. 

It would be helpful to have `quantecon-book-theme=0.1.6` released with the correct `css` file bundled.

**Comment by mmcky** [comment]
thanks for the release. @AakashGfude with `0.2.0` can this be closed or is the `hashed` files still a manual update process?

**Comment by AakashGfude** [comment]
> thanks for the release. @AakashGfude with `0.2.0` can this be closed or is the `hashed` files still a manual update process?

hashed file creation is done when committing changes, which is automatic but can be done manually as well. 
But, making releases is still manual.
