### ISSUE TITLE
Issue with labelled math

### ISSUE THREAD

**Issue by mmcky** [QuantEcon/quantecon-book-theme#12]
**Priority:** High

There is an issue with labelled math where the label proceeds the equation

<img width="1554" alt="Screen Shot 2020-10-01 at 1 10 41 pm" src="https://user-images.githubusercontent.com/8263752/94761259-e9d04000-03e7-11eb-947d-255d1da048bd.png">

While this helps with the in text linking to the equation (disappearing issue) -- it doesn't align nicely with the equation.

**Comment by AakashGfude** [comment]
@mmcky fixed in this PR: https://github.com/QuantEcon/quantecon-book-theme/pull/18
