### ISSUE TITLE
[ENH] make google analytics hash a config variable from _config.yml

### ISSUE THREAD

**Issue by mmcky** [QuantEcon/quantecon-book-theme#13]
When we deploy we should enable google analytics for each site.

It would be great if we can use:

```
html:
  google_analytics_id       : ""  # A GA id that can be used to track book views.
```

https://jupyterbook.org/customize/config.html#configuration-defaults

**Comment by mmcky** [comment]
Is this active for `quantecon-book-theme`?

**Comment by AakashGfude** [comment]
@mmcky on my list for today along with a few others assigned. will update it in the evening,

**Comment by mmcky** [comment]
This is done -- closing. thanks @DrDrij
