### ISSUE TITLE
Download of ipynb shows the raw json

### ISSUE THREAD

**Issue by mmcky** [QuantEcon/quantecon-book-theme#14]
**Priority: High**

The download `ipynb` link currently shows the raw json in the browser rather than trigger a download

https://5f7547a8d3c9a4852263d04f--epic-agnesi-957267.netlify.app/_sources/python_by_example.ipynb

**Comment by AakashGfude** [comment]
ooh, that's weird. it was downloading for me earlier. will have a look at this.

**Comment by AakashGfude** [comment]
@mmcky this should be working now: https://5f76682069785014fada1885--epic-agnesi-957267.netlify.app/about_lectures.html
