### ISSUE TITLE
Setup "view source" with a configured input from _config.yml

### ISSUE THREAD

**Issue by mmcky** [QuantEcon/quantecon-book-theme#15]
Currently the `github` button for `view source` is not working.

It would be great to use:

```
repository:
  url                       : https://github.com/executablebooks/jupyter-book  # The URL to your book's repository
  path_to_book              : ""  # A path to your book's folder, relative to the repository root.
  branch                    : master  # Which branch of the repository should be used when creating links
```

from `_config.yml` when building with `jupyter-book`

**Comment by AakashGfude** [comment]
@mmcky it should be working in https://github.com/QuantEcon/quantecon-book-theme/tree/theme-improvements. but it also depends on `test-jupyter-book` to be merged in the lectures. Will test and update this issue once that gets finalized and merged.

**Comment by mmcky** [comment]
Hey @AakashGfude that branch will fetch the latest theme master so you can merge and then just rebuilt the CI for that branch

**Comment by AakashGfude** [comment]
@mmcky ok. so you are suggesting me to merge https://github.com/QuantEcon/quantecon-book-theme/tree/theme-improvements ?

**Comment by AakashGfude** [comment]
@mmcky the `view source` should we working and downloading asset in the latest netlify https://5f76682069785014fada1885--epic-agnesi-957267.netlify.app/about_lectures.html
