### ISSUE TITLE
MAINT: Improve robustness

### ISSUE THREAD

**Issue by mmcky** [QuantEcon/quantecon-book-theme#156]
To improve robustness the `download notebook` link should only show up with `_notebooks` is found.

**Comment by mmcky** [comment]
@AakashGfude I have setup the Continuous Time Markov Chain lectures with the `quantecon` theme for `jupyter-book` but it has a link to the download notebooks. Can we wrap these download notebooks icon in an if statement and only show this element if notebooks are present when building the site.

**Comment by jstac** [comment]
Thanks guys.  (If this is too much hassle then we can just provide the notebooks.)

**Comment by mmcky** [comment]
It's no worries @jstac -- it is a quick fix.
