### ISSUE TITLE
Warning issued by jupyter-book that needs fixing

### ISSUE THREAD

**Issue by mmcky** [QuantEcon/quantecon-book-theme#16]
There is currently a warning issued by `jupyter-book` when using `quantecon-book-theme`

```
WARNING: while setting up extension quantecon_book_theme: directive 'margin' is already registered, it will be overridden
```

**Comment by AakashGfude** [comment]
@mmcky it seems this directive is not working at all as intended in the theme. looking at the error

**Comment by AakashGfude** [comment]
the theme needs styling for margin. I have suppressed the warning by adding override. but the decision on the style of the margin directive will require @DrDrij 's intervention. Will open an issue for that.

**Comment by mmcky** [comment]
@AakashGfude can we close this as there is an issue for `margin styling now`
