### ISSUE TITLE
The TOC left side bar could be closed by default

### ISSUE THREAD

**Issue by AakashGfude** [QuantEcon/quantecon-book-theme#198]

**Comment by mmcky** [comment]
@AakashGfude on my deployments this seems to be the case

**Comment by AakashGfude** [comment]
@mmcky can you let me know where did you find this case? Can't seem to find it.

**Comment by jstac** [comment]
@AakashGfude @mmcky  I think this issue came from a misunderstanding on my part and can be closed.

**Comment by AakashGfude** [comment]
ooh cool. Thanks, @jstac. I will close it.
