### ISSUE TITLE
Improve Figure Font and Format

### ISSUE THREAD

**Issue by mmcky** [QuantEcon/quantecon-book-theme#199]
When adding a caption to a figure that is generated by code the formatting could be improved

<img width="690" alt="Screenshot 2023-04-11 at 1 11 45 pm" src="https://user-images.githubusercontent.com/8263752/231046531-3e7d5f33-5a5f-4b45-bcb3-d1963422d7cc.png">

comes from this example: https://taupe-gaufre-c4e660.netlify.app/inequality.html#lorenz-us

It would be better to have:

- [ ] no italics on Fig 4.2
- [ ] no bold on remaining title text

**Comment by jstac** [comment]
Looking at some of the journals, it seems that the most common style is

**Fig 4.2.** US Lorenz curves

I suggest that we adopt this.

**Comment by AakashGfude** [comment]
Hi @jstac @mmcky , I have made the fix here along with the screenshot https://github.com/QuantEcon/quantecon-book-theme/pull/200 . This is what we are looking for?
