### ISSUE TITLE
Disable automatic Publish to PyPI

### ISSUE THREAD

**Issue by mmcky** [QuantEcon/quantecon-book-theme#2]
hey @AakashGfude not sure how this works -- but perhaps we should disable any automatic publishing to `PyPI` for now.

**Comment by AakashGfude** [comment]
@mmcky, sure. I have not set up publishing to pypi yet in this repo. That CI hook. was not working anyways. you reckon I should remove that altogether from the CI?

**Comment by mmcky** [comment]
Roger that -- Yeah let's comment it out for the time being (or remove) and document here. I imagine we will need to configure tokens etc. But let's not worry about that now.

**Comment by AakashGfude** [comment]
removed in this one https://github.com/QuantEcon/quantecon-book-theme/pull/3 .
