### ISSUE TITLE
[BUG] Hide Cell in Dark Mode

### ISSUE THREAD

**Issue by HumphreyYang** [QuantEcon/quantecon-book-theme#216]
Many thanks @AakashGfude and @mmcky,

The dark mode looks cool!

I noticed that the hide-cell component is a little bit too bright under the dark mode:

<img width="926" alt="Screenshot 2023-07-05 at 14 33 07" src="https://github.com/QuantEcon/quantecon-book-theme/assets/39026988/39fb59b9-2992-4f7b-93c7-6a6dbf336326">

**Comment by jstac** [comment]
Good catch @HumphreyYang

**Comment by AakashGfude** [comment]
Thanks @HumphreyYang , have pushed a fix here: https://github.com/QuantEcon/quantecon-book-theme/pull/215
