### ISSUE TITLE
Style margin directive

### ISSUE THREAD

**Issue by AakashGfude** [QuantEcon/quantecon-book-theme#229]
At present we have margin directive inherited from sphinx-book-theme, but it is broken:

<img width="1347" alt="Screen Shot 2023-10-05 at 11 26 17 am" src="https://github.com/QuantEcon/quantecon-book-theme/assets/6542997/096720d7-831a-4c52-b27f-f9be1d046676">

**Comment by mmcky** [comment]
@AakashGfude it would be great to get this feature supported in our theme when you have time
