### ISSUE TITLE
[Dark Theme] Text Colours for Titles and SideBar

### ISSUE THREAD

**Issue by mmcky** [QuantEcon/quantecon-book-theme#235]
![image](https://github.com/QuantEcon/lecture-python-programming.myst/assets/8263752/f2b2d9dc-154e-4b6f-942f-2a2140847ef5)

**Comment by AakashGfude** [comment]
@mmcky does this look better?

<img width="1192" alt="Screen Shot 2023-12-17 at 9 03 17 pm" src="https://github.com/QuantEcon/quantecon-book-theme/assets/6542997/8c9a0bf2-aa5c-47ac-bf9d-e6e5529330fe">
