### ISSUE TITLE
[author] Add authors below title

### ISSUE THREAD

**Issue by mmcky** [QuantEcon/quantecon-book-theme#25]
It would be nice to add `authors` to below the `title` and populated from `_config.yml` authors information. 

<img width="1609" alt="Screen Shot 2020-10-06 at 11 45 55 am" src="https://user-images.githubusercontent.com/8263752/95147086-6c337800-07cb-11eb-8a98-9cb58efd3145.png">

**Comment by jstac** [comment]
Thanks @mmcky.

Is this worth proposing to the broader JB community?

LaTeX takes title info and author info and creates a nice title page.  Some in the JB community might like to see the same thing.

What do you think?

**Comment by jstac** [comment]
I should add that I don't mind either way, regarding the direction of the broader JB community.

But I think it would be nice if our theme extracted info from the config files on title and author to make a nice front page, including title, authors and TOC.  

That way we will be able to achieve uniformity across QE lecture series, as opposed to created the landing pages individually.

**Comment by mmcky** [comment]
> Is this worth proposing to the broader JB community?

Absolutely. I will be raising an issue on `jupyter-book` repo for sure. I think variable passthrough from `_config.yml` will be useful for us (and others). 

> But I think it would be nice if our theme extracted info from the config files on title and author to make a nice front page, including title, authors and TOC.

I agree. Currently this will be `manual` and will use `intro` across the 3 quantecon projects. But an automatic title / landing page is useful for `html` -- as it is logically separate to `latex` as well so `html theme` is a good place for this. There is [an issue](https://github.com/executablebooks/sphinx-book-theme/issues/162) for this but I think in our theme we can go once step further and automate some of the things discussed in the issue. 

> re: broader community

We are currently working on `stage 1` for `quantecon-book-theme` which is a standalone theme. I should mention I have asked @AakashGfude to lead a `stage 2` process in the medium term to look at `jupyter-book` themes and investigate inheritance so `quantecon-book-theme` get's features from `sphinx-book-theme` automatically. We also have a `medium` term project to review how `jupyter-book` themes are put together in general to try and modularise the process so themes can use theme-elements with some degree of customisation.

**Comment by jstac** [comment]
Inheritance sounds like a good idea...

**Comment by mmcky** [comment]
Authors are now below the title (except front page) so closing this issue.
