### ISSUE TITLE
[home] the home button doesn't work on gh-pages and local previews

### ISSUE THREAD

**Issue by mmcky** [QuantEcon/quantecon-book-theme#28]
The home button seems to take you to the root level and therefore doesn't seem to work on `gh-pages`

https://quantecon.github.io/lecture-python-programming.myst/intro.html

**Comment by mmcky** [comment]
Same with the title in the header

**Comment by mmcky** [comment]
Maybe this would fix it?

```
baseurl                   : ""  # The base URL where your book will be hosted. Used for creating image previews and social links. e.g.: https://mypage.com/mybook/
```

https://jupyterbook.org/customize/config.html#configuration-defaults

**Comment by mmcky** [comment]
actually I would rather not use that setting because that would then break local `previews`

we should have a look at `sphinx_book_theme` to see how it is done there.

**Comment by mmcky** [comment]
Interestingly the `title`/`home` in the `lhs sidebar toc` works in `gh-pages` -- so maybe that is the template path we need to use for home?

**Comment by DrDrij** [comment]
I've linked to `intro.html` for now. There is the following option, however I think it's similar to `base_url`. It really depends on what the home file is called.
`  path_to_book              : ""  # A path to your book's folder, relative to the repository root.`

**Comment by mmcky** [comment]
could we just link to `<master_doc>.html`?

**Comment by mmcky** [comment]
thanks @DrDrij
