### ISSUE TITLE
make right hand sidebar sticky

### ISSUE THREAD

**Issue by mmcky** [QuantEcon/quantecon-book-theme#29]
@DrDrij knows about this already. 

Just documenting here as an open item. 

https://epic-agnesi-957267.netlify.app/python_by_example.html

**Comment by AakashGfude** [comment]
left sidebar as well

**Comment by mmcky** [comment]
@AakashGfude no -- the left sidebar is to be by default hidden

**Comment by AakashGfude** [comment]
@mmcky I meant once you open the left sidebar, it slides as well with the page.

**Comment by mmcky** [comment]
ah - ok I see what you mean. Thanks @AakashGfude

**Comment by mmcky** [comment]
thanks @DrDrij reverting this in #40
