### ISSUE TITLE
[review] Increase ability to find Global Toc

### ISSUE THREAD

**Issue by mmcky** [QuantEcon/quantecon-book-theme#38]
The global toc sidebar looks great and hidden by default produces a nice clean look and feel. 

It would be nice to increase the ability to find it.

One idea is:

1. bring it out of the top level header and have it as a separate "pull out style button" that is sticky and aligned with the top of the `right hand sidebar` text?

**Comment by DrDrij** [comment]
Yes I agree with this idea.
