### ISSUE TITLE
[review] Top Level Headers -- Make Both Non-Sticky

### ISSUE THREAD

**Issue by mmcky** [QuantEcon/quantecon-book-theme#39]
It would be nice to see what it would look like if both top `headers` where not sticky to get a `minimal` look when reading a lecture. 

This could be coordinated with Issue #38

**Comment by DrDrij** [comment]
I will make the tweak. The other JB themes have the right TOC highlight as you go through the sections. I can add this functionality too - but it won't be useful if the menu isn't sticky.

Let's start with clean - no stick and then adjust from there.
