### ISSUE TITLE
[review] Make RHS Contents not sticky but Keep "Back to Top" as Sticky

### ISSUE THREAD

**Issue by mmcky** [QuantEcon/quantecon-book-theme#40]
The RHS Contents sidebar creates some business when reading a lecture and focusing on content. 

It would be nice for:

1. the contents component to be not-sticky so slides of the page as you scroll down
2. Keep "back to top" as sticky

**Comment by DrDrij** [comment]
No problem - there is the jijna markup in there to have a next/previous links next to the back to top. But it doesn't appear to be passed through. Wonder if I could get some help with this one. Here is the line:

https://github.com/QuantEcon/quantecon-book-theme/blob/33d45b56a24f9d96a940eacc90049e66e5e3b45b/quantecon_book_theme/layout.html#L67

**Comment by DrDrij** [comment]
Done. https://github.com/QuantEcon/quantecon-book-theme/commit/971550d93b6aee771fb446e3fb91929a99596465
