### ISSUE TITLE
[download notebook] Add in Download IPYNB Button

### ISSUE THREAD

**Issue by mmcky** [QuantEcon/quantecon-book-theme#69]
We should get ready and add in the download IPYNB button. 

We can link this to the relevant notebooks repo such as: https://github.com/QuantEcon/lecture-python-advanced.notebooks

I am working on [sphinx-tojupyter](https://github.com/QuantEcon/sphinx-tojupyter) to support generation of these download notebooks using jupyter-book.

**Comment by DrDrij** [comment]
Noticed this is already in the master branch: https://github.com/QuantEcon/quantecon-book-theme/blob/69e0ba444295b2b211fba5536ec5633540ab69c2/quantecon_book_theme/layout.html#L192

```
                    {% if ipynb_source %}
                    <li data-tippy-content="Download Notebook"><a href="{{ pathto('_sources', 1) }}/{{ ipynb_source }}" download><i data-feather="download-cloud"></i></a></li>
                    {% endif %}
```

**Comment by mmcky** [comment]
@AakashGfude do you know what variable this is derived from in `_config.yml`

```
{% if ipynb_source %}
<li data-tippy-content="Download Notebook"><a href="{{ pathto('_sources', 1) }}/{{ ipynb_source }}" download><i data-feather="download-cloud"></i></a></li>
{% endif %}
```

as `ipynb_source` must not be defined as it isn't getting added(?). 

I might change this to be

```html
<li data-tippy-content="Download Notebook"><a href="_notebooks/{{ docname }}" download><i data-feather="download-cloud"></i></a></li>
```

but not sure what the variable is for the current `docname`?

**Comment by AakashGfude** [comment]
@mmcky so, at present this variable is set in a function ported directly from `sphinx-book-theme`. Essentially the core check for it to be able to turn on this variable is that it should have `kernelspec` metadata in the .md file. 

What checks do we want now? do we generate notebooks for every page irrespective of this metadata?

**Comment by mmcky** [comment]
hey @AakashGfude I think we can remove any checks for now and just add it in. Just not sure what the variable names are for `docname` now.

**Comment by AakashGfude** [comment]
@mmcky cool. I think the variable is `pagename`

**Comment by mmcky** [comment]
OK so I should be able to set `_notebooks/{{ pagename }}`?

**Comment by AakashGfude** [comment]
I think we should add `.ipynb` in the end possibly.
```
<li data-tippy-content="Download Notebook"><a href="_notebooks/{{ pagename }}.ipynb" download><i data-feather="download-cloud"></i></a></li>
```

**Comment by mmcky** [comment]
This is working: https://python-programming.quantecon.org/python_by_example.html

#21
