### ISSUE TITLE
BUG: Link to Source not working

### ISSUE THREAD

**Issue by mmcky** [QuantEcon/quantecon-book-theme#73]
The following Source link is not working properly

```html
<li data-tippy-content="View Source"><a target="_blank" href="{{ theme_repository_url }}{{github_sourcefolder}}/{{ sourcename }}" download><i data-feather="github"></i></a></li>
```

produces

```
https://github.com/QuantEcon/lecture-python-programming.myst/tree/master/lecture-python-programming.myst/lectures/python_by_example.md
```

i think `sourcename` must include the `github_sourcefolder`?

**Comment by AakashGfude** [comment]
@mmcky , Actually I ran the build with `sphinx-tojupyter` branch in `lecture-python-programming.myst` and it seems to be working fine.

**Comment by mmcky** [comment]
This was an issue when building within the `github actions` context due to `runners` listing the `repo` twice in the path. #77 fixes this.
