### ISSUE TITLE
[tables] Table Styles in Theme

### ISSUE THREAD

**Issue by mmcky** [QuantEcon/quantecon-book-theme#79]
@DrDrij have the table styles been migrated to this theme?

We had a `raw` html directive in our old sources but perhaps tables are now supported in a different way in this theme?

````md
```{raw} html
<div class="content-table"></div>
```
<table>
````

A recent build with a table looks like:

<img width="1443" alt="Screen Shot 2021-01-06 at 2 42 12 pm" src="https://user-images.githubusercontent.com/8263752/103726622-83357080-502d-11eb-836c-1da42e8e63fe.png">

Current Styling: https://python.quantecon.org/harrison_kreps.html#Summary-Table

**Comment by mmcky** [comment]
Also it would be nice not to need these `raw` directives to trigger the style.

**Comment by mmcky** [comment]
Current `myst` rendering once `markdown` is fixed: https://5ff53130081f8e429e9c9c0e--nostalgic-wright-5fa355.netlify.app/harrison_kreps.html

Current live site: https://python.quantecon.org/harrison_kreps.html#Summary-Table

**Comment by DrDrij** [comment]
Hopefully this is what we needed: [PR](https://github.com/QuantEcon/quantecon-book-theme/pull/94)

<img width="715" alt="image" src="https://user-images.githubusercontent.com/5886045/110888130-aa673180-833f-11eb-8a92-919c1031fd27.png">

**Comment by mmcky** [comment]
@DrDrij I think this can now be closed.
