### ISSUE TITLE
[figures] Setup centred by default?

### ISSUE THREAD

**Issue by mmcky** [QuantEcon/quantecon-book-theme#80]
Our old theme had `centred` figures by default

Comparison is available here: https://github.com/QuantEcon/lecture-python.myst/issues/21

**Comment by DrDrij** [comment]
Hopefully this is all that is needed [here](https://github.com/QuantEcon/quantecon-book-theme/pull/89)

**Comment by mmcky** [comment]
@DrDrij I think this can be now be closed.
